name: Deploy Frontend to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies and Build
        env:
          VITE_API_BASE_URL: ${{ secrets.API_BASE_URL }}
          VITE_REVERB_APP_KEY: ${{ secrets.REVERB_APP_KEY }}
          VITE_REVERB_HOST: ${{ secrets.REVERB_HOST }}
          VITE_REVERB_PORT: 443
          VITE_REVERB_SCHEME: 'https'
        run: |
          npm install
          npm run build

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          local_path: './dist/*'
          remote_path: '/home/harold-dev-front/htdocs/harold-dev.me'
          delete_remote_files: false
